services:
  db:
    image: mysql/mysql-server
    command: --authentication-policy=mysql_native_password
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=beckybot
      - MYSQL_DATABASE=beckybot
      - MYSQL_PASSWORD=FooBarIsDead
    volumes:
      - beckybot-data:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306

  redis:
    image: redis
    networks:
      - backend
    ports:
      - 6379:6379

  db-admin:
    image: adminer
    networks:
      - backend
    ports:
      - 8080:8080

  db-init:
    image: node:18-alpine
    working_dir: /src
    command: sh -c './wait-for.sh db:3306 -t 240 -- node ./db-init/init.js'
    environment:
      - DB_HOST=db
    networks:
      - backend
    volumes:
      - ./:/src

networks:
  backend:

volumes:
  beckybot-data:
