


services:
  beckybot:
    image: node:14
    command: npm run dev
    environment:
      - MYSQL_PASSWORD
      - SLACK_CLIENT_SECRET
    ports:
      - 3000:3000
      - 24678:24678
    networks:
      - traefik
      - mysql_backend
      - backend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app

  backend:
    image: node:14
    command:
      npm run dev
    environment:
      - MYSQL_PASSWORD
    networks:
      - mysql_backend
      - backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app

  redis:
    image: redis
    networks:
      - backend


networks:
  traefik:
    external: true
  mysql_backend:
    external: true
  backend:
