services:
  db-init:
    image: ghcr.io/abendigo/beckybot/db:latest
    command: node ./init.js
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - mysql_backend

  redis:
    image: redis
    networks:
      - backend

  beckybot:
    image: ghcr.io/abendigo/beckybot/frontend:latest
    environment:
      - MYSQL_PASSWORD
      - SLACK_CLIENT_SECRET
    # ports:
    #   - 3000:3000
    #   - 24678:24678
    networks:
      - traefik_default
      - mysql_backend
      - backend
    depends_on:
      db-init:
        # condition: service_completed_successfully
        condition: service_started
      redis:
        condition: service_started

  backend:
    image: ghcr.io/abendigo/beckybot/backend:latest
    environment:
      - MYSQL_PASSWORD
    networks:
      - mysql_backend
      - backend
    depends_on:
      db-init:
        # condition: service_completed_successfully
        condition: service_started
      redis:
        condition: service_started

networks:
  traefik_default:
    external: true
  mysql_backend:
    external: true
  backend:
