services:
  db:
    image: mysql/mysql-server
    restart: unless-stopped
    # command: --default-authentication-plugin=mysql_native_password
    command: --authentication-policy=mysql_native_password
    environment:
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=beckybot
      - MYSQL_DATABASE=beckybot
      - MYSQL_PASSWORD=FooBarIsDead
    networks:
      - backend
    volumes:
      # - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - beckybot-data:/var/lib/mysql

  redis:
    image: redis
    networks:
      - backend

  # db-admin:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - backend

  db-init:
    image: ghcr.io/abendigo/beckybot/db:latest
    command: sh -c './wait-for.sh db:3306 -t 0 -- node ./init.js'
    # command: node ./init.js
    # environment:
    #   - MYSQL_ROOT_PASSWORD
    depends_on:
      - db
    networks:
      - backend
    # volumes:
    #   - ./db:/src

  beckybot:
    image: ghcr.io/abendigo/beckybot/frontend:latest
    restart: unless-stopped
    #   command: npm run dev --workspace=frontend
    environment:
      - SLACK_CLIENT_SECRET
    # ports:
    #   - 3000:3000
    #     - 24678:24678
    depends_on:
      - db
      - redis
    networks:
      - traefik
      - backend
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app

  backend:
    image: ghcr.io/abendigo/beckybot/backend:latest
    restart: unless-stopped
    #   command: npm run dev --workspace=backend
    #   environment:
    #     - MYSQL_PASSWORD
    depends_on:
      - db
      - redis
    networks:
      - backend
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app

networks:
  traefik:
    name: traefik_default
    external: true
  backend:

volumes:
  beckybot-data:
