display_information:
  name: BeckyBot (Staging)
  description: Celebrating the end of the week!
  background_color: "#27292e"
features:
  bot_user:
    display_name: BeckyBotStaging
    always_online: false
oauth_config:
  redirect_urls:
    - https://beckybot.oosterveld.org/slack/oauth
  scopes:
    bot:
      - chat:write
      - channels:read
      - app_mentions:read
      - channels:history
settings:
  event_subscriptions:
    request_url: https://beckybot.oosterveld.org/slack/events
    bot_events:
      - app_mention
      - message.channels
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
