name: Backend

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - ".github/workflows/backend.yml"
      - "Dockerfile.backend"
      - "backend/**"
      - "lib/**"
  # pull_request:
  #   branches:
  #     - main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: |
      #       ghcr.io/abendigo/beckybot/backend
      #     tages: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=semver,pattern={{major}}
      #       # type=sha

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # build-args: |
          #   "NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}"
