name: Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: node --version
    - run: npm install
    - name: Test
      env:
        CUCUMBER_PUBLISH_TOKEN : ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
      run: npm test --workspace=backend -- --publish
