name: Release backend, frontend, and db-init

on:
  push:
    tags:
      - "v*"

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Extract metadata (tags, labels) for Docker (backend)
        id: backend
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/abendigo/beckybot/backend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and Push (backend)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.backend
          push: true
          tags: ${{ steps.backend.outputs.tags }}
          labels: ${{ steps.backend.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (frontend)
        id: frontend
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/abendigo/beckybot/backend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and Push (frontend)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.backend
          push: true
          tags: ${{ steps.frontend.outputs.tags }}
          labels: ${{ steps.frontend.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker (db-init)
        id: db
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/abendigo/beckybot/backend
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and Push (db-init)
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.db
          push: true
          tags: ${{ steps.db.outputs.tags }}
          labels: ${{ steps.db.outputs.labels }}
