name: Test

on: [push]

jobs:
  cucumber_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - run: npm install

      - name: Cucumber
        run: npm test
